[package]
name = "example-openapi-sse"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.2"
futures-util = "0.3.19"
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi", features = ["swagger-ui"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber = "0.3.9"
